---
- hosts: nginx
  become: yes
  roles:
    - deploy-nginx
 
- hosts: backend
  become: yes
  roles:
    - deploy-backend

- hosts: backend
  become: yes
  roles:
    - config-mysql
 