---
- name: Add config mysqld
  template:
    src: "{{ mysql_conf }}"
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  tags:
  - db_conf

- name: Create backup script
  template:
    src: db_backup
    dest: /usr/bin/db_backup
    mode: 777
  when: inventory_hostname == 'backend02'
  tags:
  - db_conf

- name: Configuration cron
  cron:
    name: "backup db"
    hour: "8"
    job: db_backup 
  when: inventory_hostname == 'backend02'
  tags:
  - db_conf
  
- name: Add recover script
  template:
    src: db_recover
    dest: /usr/bin/db_recover
    mode: 777
  tags:
  - db_conf
  when: inventory_hostname == 'backend01'

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
  tags:
  - db_conf

- name: Create user and grant privileges
  shell: |
    mysql -e "create database test_db"
    mysql -e "create user 'repl'@'%' identified by 'replTest'"
    mysql -e "grant replication slave on *.* to 'repl'@'%'"
    mysql -e "flush privileges"
  tags:
  - db_conf
  when: inventory_hostname == 'backend01'
  ignore_errors: true

- name: Configure replica
  shell: |
    mysql -e "stop replica"
    mysql -e "change replication source to source_host='192.168.122.111', source_user='repl', source_password='replTest', source_auto_position=1, get_source_public_key=1"
    mysql -e "start replica"
  tags:
  - db_conf
  when: inventory_hostname == 'backend02'
  ignore_errors: true

- name: Recover table from backup
  shell: "db_recover {{ item }}"
  loop: "{{ backup_name }}"
  tags:
  - table_recover