---
# tasks file for roles/deploy-backend
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ set_hostname }}"
  tags:
  - depl-backend
  - depl-all

#- name: Copy Netplan config
#  template:
#    src: netconf.yaml
#    dest: /etc/netplan/50-cloud-init.yaml
#  tags:
#  - depl-backend
#  - depl-all
#
#- name: Netplan Update
#  shell: 'netplan apply'
#  tags:
#  - depl-backend
#  - depl-all

- name: Update repos and install servers
  apt:
    update_cache: yes
    pkg:
    - apache2
    - mysql-server
    - tftp-hpa
    - prometheus-node-exporter
    - sshpass
    - iptables-persistent
  tags:
  - depl-backend
  - depl-all

- name: Copy iptables
  template:
    src: iptables
    dest: /etc/iptables/rules.v4
  tags:
  - depl-backend
  - depl-all

- name: Restore iptables
  shell: 'netfilter-persistent reload'
  tags:
  - depl-backend
  - depl-all

- name: Install a Filebeat package from the internet
  ansible.builtin.apt:
    deb: https://cdn.otus.ru/media/public/65/6d/filebeat_8.9.1_amd64-224190-656d53.deb
  tags:
  - depl-backend
  - depl-all

- name: Copy filebeat
  template: 
    src: filebeat
    dest: /etc/filebeat/filebeat.yml
  tags:
  - depl-backend
  - depl-all

- name: Start filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  tags:
  - depl-backend
  - depl-all

- name: Clone index.html
  git:
    repo: https://github.com/apgutech/test-site.git
    dest: /tmp/site
  tags:
  - depl-backend
  - depl-all

- name:
  shell: "mv /tmp/site/{{ index }} /var/www/html/index.html && chown www-data:www-data /var/www/html/index.html"
  tags:
  - depl-backend
  - depl-all

- name: Restart apache2
  service:
    name: apache2
    state: restarted
  tags:
  - depl-backend
  - depl-all

- name: Clean /tmp
  shell: 'rm -rf /tmp/site'
  tags:
  - depl-backend
  - depl-all