network:
    ethernets:
        ens3:
            dhcp4: false
            addresses: [ {{ ip_addr }} ]
            routes:
              - to: 0.0.0.0/0
                via: 192.168.122.1
            nameservers:
                addresses: [8.8.8.8]
    version: 2